/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Basic scaffold health check. Confirms the API is up and paths resolve.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Series
         * @description Every series discovered under ``MORPH_FOURIER_PHOTOS_ROOT``.
         */
        get: operations["list_series_api_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Series Status
         * @description All eight stage statuses for one series, keyed by stage id.
         */
        get: operations["series_status_api__series__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/curation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Curation */
        get: operations["get_curation_api__series__curation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Records
         * @description Every parsed photo in the series (with ``specimenKey`` for grouping) plus the
         *     filenames the parser could not read. The curation grid groups ``records`` by
         *     ``specimenKey``; ``unparseable`` feeds the "couldn't parse these" panel.
         */
        get: operations["get_records_api__series__records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/curation/{record_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Decision
         * @description Upsert one photo's decision, enforcing the canonical rule.
         */
        put: operations["set_decision_api__series__curation__record_key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/orient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Orient */
        get: operations["get_orient_api__series__orient_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/orient/{record_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Orientation
         * @description Persist one manual orientation (a user puck-drag → ``source = manual``).
         */
        put: operations["set_orientation_api__series__orient__record_key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/orient/build-reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Reference And Auto Orient
         * @description Build the learned reference from priming examples, then auto-orient the rest.
         */
        post: operations["build_reference_and_auto_orient_api__series__orient_build_reference_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/orient/reference-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reference Preview
         * @description Reconstruct the learned "up" outline from the reference signature.
         *
         *     The mean normalized EFA-8 vector in ``LearnedReference`` is inverse-EFA'd back
         *     to a closed outline so the user can eyeball that the learned orientation is
         *     sensible before applying it (ROADMAP §Phase 4 step 5). 404 until a reference
         *     has been built.
         */
        get: operations["reference_preview_api__series__orient_reference_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/orient/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lock Orient */
        post: operations["lock_orient_api__series__orient_lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/crop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Crop */
        get: operations["get_crop_api__series__crop_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/crop/auto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auto Crop
         * @description Auto-suggest a crop box from each canonical's cleaned mask bbox.
         *
         *     ``record_key`` set → only that canonical (the per-thumb "Auto-suggest this one");
         *     omitted → every canonical (the "Auto-suggest all" button). Either way the box is
         *     in the rotated-AND-expanded frame (each record's Stage-2 angle applied), matching
         *     what ``CropBox.tsx`` renders and what Stage 4 will crop.
         */
        post: operations["auto_crop_api__series__crop_auto_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/crop/{record_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Crop */
        put: operations["set_crop_api__series__crop__record_key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/crop/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lock Crop */
        post: operations["lock_crop_api__series__crop_lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/mask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mask */
        get: operations["get_mask_api__series__mask_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/mask/{record_key}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Standardized Image
         * @description Serve the rotated (Stage 2) + cropped (Stage 3) PNG the anchor editor draws on.
         *
         *     Anchor coordinates live in exactly this image's pixel frame, so the editor loads
         *     it as its background with no client-side coordinate math. No SAM — just a
         *     rotate+crop of the raw photo. (Phase 7's gallery reuses this endpoint.)
         *
         *     ``?w=<maxWidth>`` downscales the encoded PNG to that width (aspect preserved) for
         *     the thumbnail grid; the editor omits it to get full resolution. Responses carry a
         *     strong ETag + ``Cache-Control: no-cache`` (revalidate) so re-opening the stage is
         *     a cheap 304 when the frame is unchanged, but a re-orient/re-crop (new ETag) serves
         *     fresh pixels. Server-side, an LRU keyed on the same tuple skips regeneration.
         */
        get: operations["standardized_image_api__series__mask__record_key__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/mask/segment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Segment
         * @description Run SAM and return a simplified anchor path for the pen-tool editor.
         */
        post: operations["segment_api__series__mask_segment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/mask/{record_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Mask
         * @description Persist the anchor path, resample to an outline CSV, update mask.json.
         */
        put: operations["save_mask_api__series__mask__record_key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/mask/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lock Mask */
        post: operations["lock_mask_api__series__mask_lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/efa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Efa */
        get: operations["get_efa_api__series__efa_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/efa/calibrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calibrate
         * @description Pool cumulative-power curves across canonicals; recommend harmonic counts.
         */
        post: operations["calibrate_api__series__efa_calibrate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/efa/compute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compute
         * @description Compute EFA coefficients for all canonicals; write ``efa/coefficients.csv``.
         */
        post: operations["compute_api__series__efa_compute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/efa/reconstruct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reconstruct
         * @description Stage-6 inspector: reconstruct one specimen's outline + its power spectrum.
         */
        post: operations["reconstruct_api__series__efa_reconstruct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/pca": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pca */
        get: operations["get_pca_api__series__pca_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/pca/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pca Settings
         * @description Persisted PCA settings — carries ``harmonicsUsed`` (drift banner) and the
         *     retained-component count, without recomputing the fit. Defaults if never run.
         */
        get: operations["get_pca_settings_api__series__pca_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/pca/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Pca
         * @description Fit PCA, write scores/loadings/eigenvalues CSVs, update pca_settings.
         */
        post: operations["run_pca_api__series__pca_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/pca/reconstruct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reconstruct
         * @description Back-project a point in PC space (``{pcIndex: score}``) to a closed outline.
         */
        post: operations["reconstruct_api__series__pca_reconstruct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Taxonomy */
        get: operations["get_taxonomy_api__series__taxonomy_get"];
        /**
         * Put Taxonomy
         * @description Replace the taxonomy table (columns + assignments).
         */
        put: operations["put_taxonomy_api__series__taxonomy_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export */
        post: operations["export_api__series__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/exemplars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exemplars */
        get: operations["get_exemplars_api__series__exemplars_get"];
        /**
         * Put Exemplars
         * @description Persist the exemplar set (Prime writes this after the user primes a spread).
         */
        put: operations["put_exemplars_api__series__exemplars_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/auto-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Auto Results */
        get: operations["get_auto_results_api__series__auto_results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/automate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Automate
         * @description Run the auto pipeline over every non-primed canonical (spec §4, batch).
         *
         *     Synchronous: SAM box-predict is ~0.5 s/photo on MPS, so a ~70-photo dorsal set
         *     is ~1 min. Acceptable for the alpha; a background-task + progress-stream variant
         *     is a later option if it becomes a UX problem (see CLAUDE.md / mask 503 note).
         */
        post: operations["automate_api__series__automate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/prime/segment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prime Segment
         * @description SAM box-predict the target bone inside the user's raw-frame box (spec §4 step 2).
         *
         *     The box is the crop AND the SAM prompt (one gesture). Returns a simplified anchor
         *     path in the *cropped* (box) frame — the seed for the pen-tool editor, whose
         *     background is the same cropped region served by ``/prime/{recordKey}/image``. A
         *     box that SAM can't segment cleanly (empty / scale-card / low score) → 422 so the
         *     UI can prompt the user to redraw it.
         */
        post: operations["prime_segment_api__series__prime_segment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/prime/{record_key}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prime Image
         * @description Serve the cropped raw region (``[x1,y1,x2,y2]`` in raw-photo pixels) as a PNG.
         *
         *     This is the background the Prime anchor editor draws on: anchor coordinates from
         *     ``/prime/segment`` live in exactly this cropped frame, so the editor needs no
         *     coordinate math. No rotation — Prime masks in the box frame and applies the
         *     orientation on Save (spec §6). ``?w=`` downscales for display. Strong ETag +
         *     ``no-cache`` revalidate; an LRU skips re-decoding the raw photo.
         */
        get: operations["prime_image_api__series__prime__record_key__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/prime/exemplar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Exemplar
         * @description Assemble + persist one primed exemplar; return the updated set (spec §3 / 11C).
         *
         *     Backend-derived geometry (client ships only crop + angle + box-frame anchors):
         *       1. resample the anchor path → dense closed outline (box frame), the same
         *          authoritative resample the mask PUT uses;
         *       2. orient both into the upright frame for the display ``angleDeg``
         *          (:func:`autodetect.orient_for_display`) — the frame ``run_auto`` matches
         *          against and Stages 5–8 consume;
         *       3. normalized EFA of the oriented outline = the match key.
         *     Upserts by ``recordKey`` (re-priming a specimen replaces its exemplar).
         */
        put: operations["put_exemplar_api__series__prime_exemplar_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/prime/exemplar/{record_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Exemplar
         * @description Un-prime a specimen: drop it from the exemplar set. Idempotent (no 404 if absent).
         */
        delete: operations["delete_exemplar_api__series__prime_exemplar__record_key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{series}/review/refine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Refine
         * @description Overwrite one specimen's crop/orient/mask from a box-frame refine (spec §2, Stage 4).
         *
         *     Same inputs as ``PUT /prime/exemplar`` — a raw-frame crop box, the display angle,
         *     and a box-frame anchor path — but this writes the analysed geometry state Gallery/
         *     EFA/PCA consume, not the exemplar set. The specimen's provenance flips to a
         *     human-refined ``source="manual"`` result (unflagged), so Review re-sorts it out of
         *     the flagged-first head.
         */
        post: operations["review_refine_api__series__review_refine_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{series}/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Photo
         * @description Serve a raw source image for one series. 404 on unknown series or missing file.
         *
         *     ``filename`` is a bare name (no path segments); anything with a separator or a
         *     parent reference is rejected to prevent directory traversal outside the series
         *     folder.
         */
        get: operations["serve_photo_photos__series___filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spa Fallback
         * @description SPA fallback — every non-API route returns index.html so the React
         *     router can handle client-side navigation.
         */
        get: operations["spa_fallback__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AutoResult
         * @description Provenance for one auto-processed specimen, before Review (spec §3).
         *
         *     ``flagReason`` is one of the two top-level buckets; ``flagDetail`` keeps the
         *     specific 11A internal reason (``no_bone_colour`` | ``warm_background`` |
         *     ``low_sam_score`` | ``scale_card`` | ``segmentation_failed``) for the UI.
         */
        AutoResult: {
            /** Recordkey */
            recordKey: string;
            /**
             * Source
             * @enum {string}
             */
            source: "auto" | "manual" | "primed";
            /** Matchedexemplarkey */
            matchedExemplarKey?: string | null;
            /** Matchdistance */
            matchDistance?: number | null;
            /**
             * Flagged
             * @default false
             */
            flagged: boolean;
            /** Flagreason */
            flagReason?: ("low_confidence" | "detection_failed") | null;
            /** Flagdetail */
            flagDetail?: string | null;
        };
        /**
         * AutoResultsState
         * @description Per-series auto-processing provenance (``auto_results.json``).
         */
        AutoResultsState: {
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
            /** Updatedat */
            updatedAt: string;
            /**
             * Results
             * @default {}
             */
            results: {
                [key: string]: components["schemas"]["AutoResult"];
            };
        };
        /**
         * AutomateSummary
         * @description Return of ``POST /api/{series}/automate`` — one batch's outcome counts.
         */
        AutomateSummary: {
            /** Serieskey */
            seriesKey: string;
            /** Processed */
            processed: number;
            /**
             * Primed
             * @default 0
             */
            primed: number;
            /**
             * Knowngoodpreserved
             * @default 0
             */
            knownGoodPreserved: number;
            /** Autoisolated */
            autoIsolated: number;
            /** Matched */
            matched: number;
            /** Flagged */
            flagged: number;
            /** Flaggedlowconfidence */
            flaggedLowConfidence: number;
            /** Flaggeddetectionfailed */
            flaggedDetectionFailed: number;
            /** Elapsedseconds */
            elapsedSeconds: number;
            /**
             * Skippednoexemplars
             * @default false
             */
            skippedNoExemplars: boolean;
        };
        /** CalibrationResult */
        CalibrationResult: {
            /** Meancurve */
            meanCurve: number[];
            /** Recommended */
            recommended: components["schemas"]["RecommendedHarmonic"][];
            /** Nspecimens */
            nSpecimens: number;
        };
        /** CropBox */
        CropBox: {
            /** X1 */
            x1: number;
            /** Y1 */
            y1: number;
            /** X2 */
            x2: number;
            /** Y2 */
            y2: number;
            /**
             * Source
             * @enum {string}
             */
            source: "auto" | "manual";
        };
        /** CropState */
        CropState: {
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
            /** Updatedat */
            updatedAt: string;
            /** Lockedat */
            lockedAt?: string | null;
            /**
             * Crops
             * @default {}
             */
            crops: {
                [key: string]: components["schemas"]["CropBox"];
            };
        };
        /** CurationState */
        CurationState: {
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
            /** Updatedat */
            updatedAt: string;
            /**
             * Photos
             * @default {}
             */
            photos: {
                [key: string]: components["schemas"]["PhotoDecision"];
            };
        };
        /** EfaComputeRequest */
        EfaComputeRequest: {
            /** Harmonics */
            harmonics?: number | null;
            /** Normalize */
            normalize?: boolean | null;
            /** Anchor */
            anchor?: ("top" | "bottom" | "left" | "right") | null;
        };
        /** EfaReconstructRequest */
        EfaReconstructRequest: {
            /** Recordkey */
            recordKey: string;
            /** Harmonics */
            harmonics?: number | null;
            /**
             * Normalize
             * @default true
             */
            normalize: boolean;
            /**
             * Anchor
             * @default top
             */
            anchor: ("top" | "bottom" | "left" | "right");
        };
        /** EfaSettings */
        EfaSettings: {
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
            /** Lastcomputedat */
            lastComputedAt?: string | null;
            /**
             * Harmonics
             * @default 12
             */
            harmonics: number;
            /**
             * Normalize
             * @default true
             */
            normalize: boolean;
            /**
             * Anchor
             * @default top
             */
            anchor: ("top" | "bottom" | "left" | "right");
            /**
             * Nspecimenscomputed
             * @default 0
             */
            nSpecimensComputed: number;
        };
        /**
         * Exemplar
         * @description A fully-processed primed training specimen (the "training data").
         */
        Exemplar: {
            /** Recordkey */
            recordKey: string;
            cropBox: components["schemas"]["CropBox"];
            /** Angledeg */
            angleDeg: number;
            /** Anchorpath */
            anchorPath: components["schemas"]["Point"][];
            /** Outline */
            outline: components["schemas"]["Point"][];
            /** Efacoeffs */
            efaCoeffs: number[][];
        };
        /**
         * ExemplarSet
         * @description The exemplar set = the learned model for one series (``exemplars.json``).
         */
        ExemplarSet: {
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
            /**
             * Harmonics
             * @default 8
             */
            harmonics: number;
            /**
             * Exemplars
             * @default []
             */
            exemplars: components["schemas"]["Exemplar"][];
        };
        /** ExportResult */
        ExportResult: {
            /** Manifestpath */
            manifestPath: string;
            /** Exportedcount */
            exportedCount: number;
            /**
             * Skipped
             * @default []
             */
            skipped: components["schemas"]["ExportSkip"][];
        };
        /** ExportSkip */
        ExportSkip: {
            /** Recordkey */
            recordKey: string;
            /** Reason */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LearnedReference */
        LearnedReference: {
            /** Primingrecordkeys */
            primingRecordKeys: string[];
            /** Referencecoeffs */
            referenceCoeffs: number[];
            /** Harmonicsused */
            harmonicsUsed: number;
            /** Builtat */
            builtAt: string;
        };
        /** MaskEntry */
        MaskEntry: {
            /**
             * Seedpoints
             * @default []
             */
            seedPoints: components["schemas"]["SeedPoint"][];
            /** Anchorpath */
            anchorPath?: components["schemas"]["Point"][] | null;
            /**
             * Source
             * @enum {string}
             */
            source: "auto" | "manual";
            /** Outlinepointcount */
            outlinePointCount: number;
            /** Outlinerelpath */
            outlineRelPath: string;
        };
        /** MaskState */
        MaskState: {
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
            /** Updatedat */
            updatedAt: string;
            /** Lockedat */
            lockedAt?: string | null;
            /**
             * Masks
             * @default {}
             */
            masks: {
                [key: string]: components["schemas"]["MaskEntry"];
            };
        };
        /**
         * MaskUpdateRequest
         * @description PUT /mask/{recordKey}: persist the (possibly edited) anchor path.
         */
        MaskUpdateRequest: {
            /** Recordkey */
            recordKey: string;
            /** Anchorpath */
            anchorPath: components["schemas"]["Point"][];
            /**
             * Seedpoints
             * @default []
             */
            seedPoints: components["schemas"]["SeedPoint"][];
            /**
             * Source
             * @default manual
             * @enum {string}
             */
            source: "auto" | "manual";
        };
        /** OrientState */
        OrientState: {
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
            /** Updatedat */
            updatedAt: string;
            /** Lockedat */
            lockedAt?: string | null;
            /**
             * Orientations
             * @default {}
             */
            orientations: {
                [key: string]: components["schemas"]["Orientation"];
            };
            learnedReference?: components["schemas"]["LearnedReference"] | null;
        };
        /** Orientation */
        Orientation: {
            /** Angledeg */
            angleDeg: number;
            /**
             * Source
             * @enum {string}
             */
            source: "manual" | "learned";
            /**
             * Isprimingexample
             * @default false
             */
            isPrimingExample: boolean;
        };
        /** PcaReconstructRequest */
        PcaReconstructRequest: {
            /**
             * Pcvalues
             * @default {}
             */
            pcValues: {
                [key: string]: number;
            };
        };
        /** PcaResult */
        PcaResult: {
            /** Specimenids */
            specimenIds: string[];
            /** Scores */
            scores: number[][];
            /** Varratio */
            varRatio: number[];
            /** Cumvarratio */
            cumVarRatio: number[];
            /** Loadings */
            loadings: number[][];
            /** Mean */
            mean: number[];
            /** Featurenames */
            featureNames: string[];
            /** Ncomponents */
            nComponents: number;
        };
        /** PcaRunRequest */
        PcaRunRequest: {
            /** Ncomponentsretained */
            nComponentsRetained?: number | null;
            /** Variancetarget */
            varianceTarget?: number | null;
            /** Excludedspecimens */
            excludedSpecimens?: string[] | null;
        };
        /** PcaSettings */
        PcaSettings: {
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
            /** Lastcomputedat */
            lastComputedAt?: string | null;
            /** Ncomponentsretained */
            nComponentsRetained?: number | null;
            /**
             * Variancetarget
             * @default 0.95
             */
            varianceTarget: number;
            /**
             * Ncomponentstotal
             * @default 0
             */
            nComponentsTotal: number;
            /** Harmonicsused */
            harmonicsUsed?: number | null;
            /**
             * Excludedspecimens
             * @default []
             */
            excludedSpecimens: string[];
        };
        /** PhotoDecision */
        PhotoDecision: {
            /**
             * Status
             * @enum {string}
             */
            status: "unreviewed" | "accepted" | "rejected";
            /** Rejectionreason */
            rejectionReason?: string | null;
            /**
             * Iscanonical
             * @default false
             */
            isCanonical: boolean;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** PhotoRecord */
        PhotoRecord: {
            /** Recordkey */
            recordKey: string;
            /** Serieskey */
            seriesKey: string;
            /** Filename */
            filename: string;
            /** Specimenid */
            specimenId: string;
            /** Specimenidsafe */
            specimenIdSafe: string;
            /** Specimenkey */
            specimenKey: string;
            /** Label */
            label: string;
            /** Photoindex */
            photoIndex: number;
        };
        /** Point */
        Point: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * PrimeExemplarRequest
         * @description PUT /prime/exemplar: persist one primed exemplar (Prime writes this per specimen).
         *
         *     The client sends only the raw materials — ``cropBox`` (raw frame), the display
         *     ``angleDeg`` the puck set, and the refined ``anchorPath`` in the *box* frame. The
         *     backend derives everything else (dense oriented outline + normalized ``efaCoeffs``),
         *     so the EFA math stays server-side (spec §3 / 11C). Upserts into ``exemplars.json``.
         */
        PrimeExemplarRequest: {
            /** Recordkey */
            recordKey: string;
            cropBox: components["schemas"]["CropBox"];
            /** Angledeg */
            angleDeg: number;
            /** Anchorpath */
            anchorPath: components["schemas"]["Point"][];
        };
        /**
         * PrimeSegmentRequest
         * @description POST /prime/segment: SAM box-predict inside a RAW-frame box (crop-before-orient).
         *
         *     ``box`` is the crop the user drew on the raw photo — it is both the crop and the
         *     SAM prompt (spec §4). Returns a :class:`SegmentResult` whose anchor coords live in
         *     the cropped (box) frame, matching the cropped image the editor draws on.
         */
        PrimeSegmentRequest: {
            /** Recordkey */
            recordKey: string;
            box: components["schemas"]["CropBox"];
        };
        /** RecommendedHarmonic */
        RecommendedHarmonic: {
            /** Threshold */
            threshold: number;
            /** Harmonics */
            harmonics: number;
        };
        /** ReconstructResult */
        ReconstructResult: {
            /** Outline */
            outline: components["schemas"]["Point"][];
            /** Powerspectrum */
            powerSpectrum?: number[] | null;
        };
        /** SeedPoint */
        SeedPoint: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /**
             * Label
             * @enum {integer}
             */
            label: 0 | 1;
        };
        /** SegmentRequest */
        SegmentRequest: {
            /** Recordkey */
            recordKey: string;
            /**
             * Seedpoints
             * @default []
             */
            seedPoints: components["schemas"]["SeedPoint"][];
        };
        /** SegmentResult */
        SegmentResult: {
            /** Anchorpath */
            anchorPath: components["schemas"]["Point"][];
            /** Outlinepointcount */
            outlinePointCount: number;
        };
        /** Series */
        Series: {
            /** Key */
            key: string;
            /** Displayname */
            displayName: string;
            /** Photocount */
            photoCount: number;
        };
        /**
         * SeriesRecords
         * @description Envelope for ``GET /api/{series}/records`` — every parsed photo in a series
         *     plus the filenames that did not parse (surfaced, never silently dropped).
         */
        SeriesRecords: {
            /**
             * Records
             * @default []
             */
            records: components["schemas"]["PhotoRecord"][];
            /**
             * Unparseable
             * @default []
             */
            unparseable: string[];
        };
        /** StageStatus */
        StageStatus: {
            /** Serieskey */
            seriesKey: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /** Lastcomputedat */
            lastComputedAt?: string | null;
            /**
             * Readycount
             * @default 0
             */
            readyCount: number;
            /**
             * Totalcanonicals
             * @default 0
             */
            totalCanonicals: number;
        };
        /** TaxonomyColumn */
        TaxonomyColumn: {
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "categorical" | "numeric";
        };
        /** TaxonomyState */
        TaxonomyState: {
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
            /** Updatedat */
            updatedAt: string;
            /**
             * Columns
             * @default []
             */
            columns: components["schemas"]["TaxonomyColumn"][];
            /**
             * Assignments
             * @default {}
             */
            assignments: {
                [key: string]: {
                    [key: string]: string | number | null;
                };
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_series_api_series_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Series"][];
                };
            };
        };
    };
    series_status_api__series__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["StageStatus"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_curation_api__series__curation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_records_api__series__records_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesRecords"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_decision_api__series__curation__record_key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
                record_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_orient_api__series__orient_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrientState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_orientation_api__series__orient__record_key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
                record_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Orientation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrientState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_reference_and_auto_orient_api__series__orient_build_reference_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrientState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reference_preview_api__series__orient_reference_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconstructResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_orient_api__series__orient_lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrientState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crop_api__series__crop_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CropState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auto_crop_api__series__crop_auto_post: {
        parameters: {
            query?: {
                /** @description Suggest for just this canonical; omit to (re)suggest for all. */
                recordKey?: string | null;
            };
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CropState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_crop_api__series__crop__record_key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
                record_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CropBox"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CropState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_crop_api__series__crop_lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CropState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mask_api__series__mask_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaskState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    standardized_image_api__series__mask__record_key__image_get: {
        parameters: {
            query?: {
                w?: number | null;
            };
            header?: never;
            path: {
                series: string;
                record_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    segment_api__series__mask_segment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_mask_api__series__mask__record_key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
                record_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaskUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaskState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_mask_api__series__mask_lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaskState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_efa_api__series__efa_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EfaSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calibrate_api__series__efa_calibrate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_api__series__efa_compute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EfaComputeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EfaSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconstruct_api__series__efa_reconstruct_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EfaReconstructRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconstructResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pca_api__series__pca_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PcaResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pca_settings_api__series__pca_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PcaSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_pca_api__series__pca_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PcaRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PcaResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconstruct_api__series__pca_reconstruct_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PcaReconstructRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconstructResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_taxonomy_api__series__taxonomy_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_taxonomy_api__series__taxonomy_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxonomyState"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api__series__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exemplars_api__series__exemplars_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExemplarSet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_exemplars_api__series__exemplars_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExemplarSet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExemplarSet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_auto_results_api__series__auto_results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoResultsState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    automate_api__series__automate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutomateSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prime_segment_api__series__prime_segment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrimeSegmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prime_image_api__series__prime__record_key__image_get: {
        parameters: {
            query: {
                x1: number;
                y1: number;
                x2: number;
                y2: number;
                w?: number | null;
            };
            header?: never;
            path: {
                series: string;
                record_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_exemplar_api__series__prime_exemplar_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrimeExemplarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExemplarSet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_exemplar_api__series__prime_exemplar__record_key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
                record_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExemplarSet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_refine_api__series__review_refine_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrimeExemplarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_photo_photos__series___filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spa_fallback__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
